/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Sound;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Classes.ManipularImagem;
import Conexao.conexao;
import static Conexao.conexao.statement;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;

/**
 *
 * @author Shut
 */
public class Recipes extends javax.swing.JFrame {
    //Conversão imagem
    byte[] byteArray = null;  
    File f;
    
    byte[] imgreceita;
    
    //Imagem do negocio
    BufferedImage imagem;    
    
    public Recipes() {
        initComponents();
         
        //Música
        Sound.fund.play();

        ImageIcon imageIcon = new ImageIcon(new ImageIcon("Imgs/jac.png").getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT));
        jac.setIcon(imageIcon);
        
        mostrarnomereceita();
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receita = new javax.swing.JTextField();
        Textdivider = new javax.swing.JLabel();
        deletarreceita = new javax.swing.JLabel();
        Inserirbtn = new javax.swing.JLabel();
        vidbtn = new javax.swing.JLabel();
        imgbtn = new javax.swing.JLabel();
        lbdigit = new javax.swing.JLabel();
        lbrestam = new javax.swing.JLabel();
        lbreceitas = new javax.swing.JLabel();
        fod = new javax.swing.JLabel();
        jacq = new javax.swing.JLabel();
        vid = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jac_borda = new javax.swing.JLabel();
        jac = new javax.swing.JLabel();
        rec = new javax.swing.JLabel();
        receitas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        insertreceita = new javax.swing.JTextArea();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receita.setBackground(new java.awt.Color(47, 48, 52));
        receita.setFont(new java.awt.Font("Blackadder ITC", 1, 30)); // NOI18N
        receita.setForeground(new java.awt.Color(218, 165, 32));
        receita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receitaActionPerformed(evt);
            }
        });
        getContentPane().add(receita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 480, 30));

        Textdivider.setFont(new java.awt.Font("Edwardian Script ITC", 1, 90)); // NOI18N
        Textdivider.setForeground(new java.awt.Color(218, 165, 32));
        Textdivider.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 165, 32), 1, true));
        getContentPane().add(Textdivider, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 820, 10));

        deletarreceita.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        deletarreceita.setForeground(new java.awt.Color(218, 165, 32));
        deletarreceita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletarreceita.setText("Deletar Receita");
        deletarreceita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 165, 32), 1, true));
        deletarreceita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletarreceitaMouseClicked(evt);
            }
        });
        getContentPane().add(deletarreceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 360, 40));

        Inserirbtn.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        Inserirbtn.setForeground(new java.awt.Color(218, 165, 32));
        Inserirbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inserirbtn.setText("Inserir Receita");
        Inserirbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 165, 32), 1, true));
        Inserirbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Inserirbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 360, 40));

        vidbtn.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        vidbtn.setForeground(new java.awt.Color(218, 165, 32));
        vidbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vidbtn.setText("Vídeo");
        vidbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 165, 32), 1, true));
        vidbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vidbtnMouseClicked(evt);
            }
        });
        getContentPane().add(vidbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 160, 40));

        imgbtn.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        imgbtn.setForeground(new java.awt.Color(218, 165, 32));
        imgbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgbtn.setText("Imagem");
        imgbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 165, 32), 1, true));
        imgbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgbtnMouseClicked(evt);
            }
        });
        getContentPane().add(imgbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 160, 40));

        lbdigit.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        lbdigit.setForeground(new java.awt.Color(218, 165, 32));
        lbdigit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbdigit.setText("400");
        getContentPane().add(lbdigit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 660, 80, 40));

        lbrestam.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        lbrestam.setForeground(new java.awt.Color(218, 165, 32));
        lbrestam.setText("Restam:");
        getContentPane().add(lbrestam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 130, 40));

        lbreceitas.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        lbreceitas.setForeground(new java.awt.Color(218, 165, 32));
        lbreceitas.setText("Receitas:");
        getContentPane().add(lbreceitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 90));

        fod.setFont(new java.awt.Font("Edwardian Script ITC", 1, 90)); // NOI18N
        fod.setForeground(new java.awt.Color(218, 165, 32));
        fod.setText("Do");
        getContentPane().add(fod, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 130, 90));

        jacq.setFont(new java.awt.Font("Edwardian Script ITC", 1, 90)); // NOI18N
        jacq.setForeground(new java.awt.Color(218, 165, 32));
        jacq.setText(" Jacquin");
        getContentPane().add(jacq, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 270, 100));

        vid.setFont(new java.awt.Font("Edwardian Script ITC", 1, 90)); // NOI18N
        vid.setForeground(new java.awt.Color(218, 165, 32));
        vid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 165, 32), 2, true));
        getContentPane().add(vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 160, 160));

        img.setFont(new java.awt.Font("Edwardian Script ITC", 1, 90)); // NOI18N
        img.setForeground(new java.awt.Color(218, 165, 32));
        img.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 165, 32), 2, true));
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 160, 160));

        jac_borda.setFont(new java.awt.Font("Edwardian Script ITC", 1, 90)); // NOI18N
        jac_borda.setForeground(new java.awt.Color(218, 165, 32));
        jac_borda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 165, 32), 2, true));
        getContentPane().add(jac_borda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 170, 150));

        jac.setFont(new java.awt.Font("Edwardian Script ITC", 1, 90)); // NOI18N
        jac.setForeground(new java.awt.Color(218, 165, 32));
        getContentPane().add(jac, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, 130));

        rec.setFont(new java.awt.Font("Edwardian Script ITC", 1, 90)); // NOI18N
        rec.setForeground(new java.awt.Color(218, 165, 32));
        rec.setText("Receitas");
        getContentPane().add(rec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 290, 90));

        receitas.setBackground(new java.awt.Color(218, 165, 32));
        receitas.setEditable(true);
        receitas.setFont(new java.awt.Font("Blackadder ITC", 0, 30)); // NOI18N
        receitas.setForeground(new java.awt.Color(51, 51, 51));
        receitas.setMaximumRowCount(100);
        receitas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                receitasItemStateChanged(evt);
            }
        });
        receitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receitasActionPerformed(evt);
            }
        });
        getContentPane().add(receitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 350, 30));

        insertreceita.setBackground(new java.awt.Color(47, 48, 52));
        insertreceita.setColumns(20);
        insertreceita.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        insertreceita.setForeground(new java.awt.Color(218, 165, 32));
        insertreceita.setRows(5);
        insertreceita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                insertreceitaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(insertreceita);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 480, 350));

        wallpaper.setFont(new java.awt.Font("Edwardian Script ITC", 1, 90)); // NOI18N
        wallpaper.setForeground(new java.awt.Color(218, 165, 32));
        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/wallpaper.png"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertreceitaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insertreceitaKeyTyped
    caracteres_faltando();    
    }//GEN-LAST:event_insertreceitaKeyTyped
    private void caracteres_faltando(){
    
        int maxDig = 400;
        int totalDig = 400;

        if (insertreceita.getText().length() > maxDig)
        {
            JOptionPane.showMessageDialog(null, "Excedeu o numero maximo de caracteres");
            totalDig = 0;
            insertreceita.setText(insertreceita.getText().substring(0, maxDig));
            return;
        }

        for (int x=0; x < insertreceita.getText().length(); x++)
        {
            totalDig = totalDig - 1;
        }

        lbdigit.setText(String.valueOf(totalDig)); 
    }
    private void receitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receitasActionPerformed

    }//GEN-LAST:event_receitasActionPerformed

    private void InserirbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirbtnMouseClicked
    salvar();
    
    receitas.removeAll();
    
    mostrarreceita();
    }//GEN-LAST:event_InserirbtnMouseClicked

    private void salvar(){     
    try{ 
        
        String sql = "Insert into tb00_receitas(tb00_nome_receita,tb00_receita,tb00_img) VALUES ('" + receita.getText() +"', '" + insertreceita.getText() + "', '" + imagem + "');";
        conexao BD = new conexao();
        BD.conectar();
        ResultSet dados = null; 
              
        statement.executeUpdate(sql);            
            
        BD.desconectar();
        dados.close();
        statement.close();  

        }
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
    }  
    
    private void mostrarimg(){     
    try{ 
        
        String sql = "Select tb00_img from tb00_receitas where tb00_id = 2";
        conexao BD = new conexao();
        BD.conectar();
        ResultSet dados = null; 
            
        dados = statement.executeQuery(sql);            

        if(dados.next())
        {
            
            Blob ablob = dados.getBlob("tb00_img");  
            InputStream is = ablob.getBinaryStream(0, ablob.length());
            BufferedImage imag = ImageIO.read(is);
            Image image = imag;
            ImageIcon icon = new ImageIcon(image);
            vid.setIcon(icon); 
          
        }
        
        BD.desconectar();
        dados.close();
        statement.close();  
        
        }
        
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
    }
    
    private void mostrarnomereceita(){ 
        try{ 
            String sql = "Select * from tb00_receitas" ;
            
            conexao BD = new conexao();
            BD.conectar();
            ResultSet dados = null; 
            
            dados = statement.executeQuery(sql);  
        
            String[] row = new String[1];
            
            
        while(dados.next())
        {
            
          row[0] = dados.getString("tb00_nome_receita");
          
          receitas.addItem(row[0]);
          
        }
        
        mostrarreceita();
        receita.setText(String.valueOf(receitas.getSelectedItem()));
        
        BD.desconectar();
        dados.close();
        statement.close();  
        
        }
        
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        }
    }
    
    private void mostrarreceita(){ 
        try{ 
            String sql = "Select * from tb00_receitas where tb00_nome_receita = '" + receitas.getSelectedItem() + "'";
            
            conexao BD = new conexao();
            BD.conectar();
            ResultSet dados = null; 
            
            dados = statement.executeQuery(sql);  
        
            String[] row = new String[1];
            
            
        while(dados.next())
        {
            
          row[0] = dados.getString("tb00_receita");
          
          insertreceita.setText(row[0]);
          
        }
        
        caracteres_faltando();
        
        BD.desconectar();
        dados.close();
        statement.close();  
        
        }
        
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        }
    }
    
    private void deletar(){
        try{
            int sim_nao = JOptionPane.YES_NO_OPTION;
            
            sim_nao = JOptionPane.showConfirmDialog(null, "Certeza que quer excluir '" + receita.getText() + "'?");
            
            if(sim_nao == JOptionPane.YES_OPTION){
                
                String sql = "Delete from tb00_receitas where tb00_nome_receita = '" + receita.getText() + "'";
                conexao BD = new conexao();
                BD.conectar();          
                statement.executeUpdate(sql);
                
                BD.desconectar();
                statement.close();
                
            }            
        }

        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    private void imgbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgbtnMouseClicked
        
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            try {
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 160, 160);
                
                img.setIcon(new ImageIcon(imagem));
                
                int wi;
                wi = (int)ManipularImagem.width_imagem;
                
                int he;
                he = (int)ManipularImagem.height_imagem;
                
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(),wi, he);
                
                f = arquivo;
                
            } catch (Exception ex) {
            }

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
    }//GEN-LAST:event_imgbtnMouseClicked

    private void vidbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vidbtnMouseClicked
    mostrarimg();
    }//GEN-LAST:event_vidbtnMouseClicked

    private void receitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receitaActionPerformed

    }//GEN-LAST:event_receitaActionPerformed

    private void receitasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_receitasItemStateChanged
        mostrarreceita();
        receita.setText(String.valueOf(receitas.getSelectedItem()));
    }//GEN-LAST:event_receitasItemStateChanged

    private void deletarreceitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletarreceitaMouseClicked
        deletar();
        
        receitas.removeAll();
        
        mostrarreceita();       
        mostrarnomereceita();
    }//GEN-LAST:event_deletarreceitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recipes().setVisible(true);
   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inserirbtn;
    private javax.swing.JLabel Textdivider;
    private javax.swing.JLabel deletarreceita;
    private javax.swing.JLabel fod;
    private javax.swing.JLabel img;
    private javax.swing.JLabel imgbtn;
    private javax.swing.JTextArea insertreceita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jac;
    private javax.swing.JLabel jac_borda;
    private javax.swing.JLabel jacq;
    private javax.swing.JLabel lbdigit;
    private javax.swing.JLabel lbreceitas;
    private javax.swing.JLabel lbrestam;
    private javax.swing.JLabel rec;
    private javax.swing.JTextField receita;
    private javax.swing.JComboBox<String> receitas;
    private javax.swing.JLabel vid;
    private javax.swing.JLabel vidbtn;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
